//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Prestamo
    {
        public int ID_Registro { get; set; }
        public Nullable<System.DateTime> Fecha_uso { get; set; }
        public Nullable<int> monto_usado { get; set; }
        public string Transaccion { get; set; }
        public Nullable<int> ID_Prestamo { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
    }
}
