//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Prestamo
    {
        public int ID_Registro { get; set; }
        public Nullable<System.DateTime> Fecha_uso { get; set; }
        public Nullable<int> monto_usado { get; set; }
        public string Transaccion { get; set; }
        public Nullable<int> ID_Prestamo { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
    }
}
