//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta_credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta_credito()
        {
            this.Registro_Tarjeta = new HashSet<Registro_Tarjeta>();
        }
    
        public int ID_Tarjeta { get; set; }
        public Nullable<int> ID_propietario { get; set; }
        public Nullable<int> Tarjeta_monto { get; set; }
        public Nullable<System.DateTime> Fecha_limiteapagar { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_Tarjeta> Registro_Tarjeta { get; set; }
    }
}
