//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta_credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta_credito()
        {
            this.Registro_Tarjeta1 = new HashSet<Registro_Tarjeta>();
        }
    
        public int ID_Tarjeta { get; set; }
        public Nullable<int> ID_propietario { get; set; }
        public Nullable<int> Tarjeta_monto { get; set; }
        public Nullable<System.DateTime> Fecha_limiteapagar { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Registro_Tarjeta Registro_Tarjeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_Tarjeta> Registro_Tarjeta1 { get; set; }
    }
}
